### ISSUE TITLE
Suggested supported additions for charts - Sunburst, Data Table, Multiline

### ISSUE THREAD

**Issue by edwardtilley** [app-generator/boilerplate-code-flask-dashboard#1]
Can I suggest that a few common dashboard elements would be good examples - data table - resortable and filterable , sunburst - clickable with other screens reacting to clicks of leafs, multi-line charts - I pull world bank stats using python and wbdata apis for example...

**Comment by app-generator** [comment]
For enhancements please use the [official AppSeed board](https://appseed.nolt.io/)
Closing the issue.
