### ISSUE TITLE
Update all dependencies to latest versions

### ISSUE THREAD

**Issue by siparker** [app-generator/boilerplate-code-flask-dashboard#10]
Update the requirements.txt file to the latest version of each dependency

flask==2.0.1
flask_login==0.5.0
flask_migrate==3.1.0
flask_wtf==0.15.1
flask_sqlalchemy==2.5.1
sqlalchemy==1.4.23
email_validator==1.1.3
python-decouple==3.4
gunicorn==20.0.4
jinja2==3.0.1

The only change required in the code is to change Binary to LargeBinary in the /base/models.py lines 7 and 20

**Comment by ksh7** [comment]
Done

**Comment by app-generator** [comment]
Hello @siparker,

Ty for your patch
