### ISSUE TITLE
404 error handler not rendering

### ISSUE THREAD

**Issue by Daniyaldehleh** [app-generator/boilerplate-code-flask-dashboard#2]
[This](https://github.com/app-generator/flask-black-dashboard/blob/master/app/base/routes.py#L114-L116) handler is not getting called upon 404, resulting in default 404 page from flask. 
```
@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

```
Possibly useful links: https://flask.palletsprojects.com/en/1.1.x/blueprints/#error-handlers

**Comment by app-generator** [comment]
Fixed in **v2.0.0**.
