### ISSUE TITLE
Error in javascript when open menu

### ISSUE THREAD

**Issue by paulo-coutinho** [app-generator/boilerplate-code-flask-dashboard#4]
Thanks for this great project, first!

I downloaded now your project and when i open the dashboard and click on hamburguer menu to open side menu i get this error:

![image](https://user-images.githubusercontent.com/395096/116461291-74720400-a83e-11eb-911d-afec325ca897.png)

Can you help me?

**Comment by app-generator** [comment]
Fixed in **v2.0.0**.
